### ISSUE TITLE
Missing files in the dataset drive

### ISSUE THREAD

**Issue by loicland** [Depanshu-Sani/SICKLE#3]
Hi,

thanks for the cool dataset. I was granted access to the data, but I noticed that some files are missing:
- all S2 time series
- sickle_dataset_tabular.csv

Could you please update it on the drive?

Thanks a lot!

PS: any idea of when you'll release the test set as well?

**Comment by Depanshu-Sani** [comment]
Hi Loic,
Thank you for showing interest in our work. 
I tried downloading the dataset using the drive link and was able to locate all the files (including the ones you mentioned). I don't know what the issue here is. Since the number of files (and folders) is very high, as shown in the figure below, it might take a significant amount of time to extract the dataset from the zip. I would suggest you verify whether the extraction was successful.
![image](https://github.com/user-attachments/assets/3335ee32-7124-45eb-ad54-82d2c8daff27)

Moreover, we are currently working on hosting the test set. However, it will still take some time. Thank you for your patience!

_Please feel free to re-open the issue if you think there is still some issue._

**Comment by loicland** [comment]
You were correct, it was an issue with the unzipping.

Thanks!
